spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=rscbillingmaster
    username: postgres
    password: password
  client:
   serviceUrl:
     defaultZone: http://localhost:8080/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"     
     
